name: ncval
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - xarray
  - netCDF4
  - numpy
  - scipy
  - pandas
  - dask
  - gdal
  - rioxarray
  - rasterio
  - pyproj
  - pyresample
  - xesmf
  - matplotlib
  - cartopy
